### ISSUE TITLE
Select stations

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [seisman/HinetPy#19]
Hi,

The circular region selection of stations appears to be broken. The example [here](https://seisman.github.io/HinetPy/api/HinetPy.client.html?highlight=select_stations#HinetPy.client.Client.select_stations):
```
>>> client.select_stations('0101', latitude=30, longitude139,
...                        minradius=0, maxradius=2)
```

produces the following error stack:
```
Traceback (most recent call last):
  File "download.py", line 285, in <module>
    hinet.download_event_data(events, args.maxradius)
  File "download.py", line 247, in download_event_data
    fn = self.event_to_stations(event, maxradius)
  File "download.py", line 225, in event_to_stations
    minradius=0, maxradius=2)
  File "/home/marius/.local/lib/python3.5/site-packages/HinetPy/client.py", line 1049, in select_stations
    stations_at_server = self.get_station_list(code)
  File "/home/marius/.local/lib/python3.5/site-packages/HinetPy/client.py", line 903, in get_station_list
    latitude, longitude, elevation = items[7], items[8], items[12]
IndexError: list index out of range
```

Also, there is a typo in the example (longitude139)

**Comment by seisman** [comment]
Hi-net recently changed the CSV format of stations information file. I've made changes, now it should work.
