### ISSUE TITLE
Connecting Hinet time out over a period of time

### ISSUE THREAD

**Issue by xumi1993** [seisman/HinetPy#7]
Hi Dongdong,
Great work for HinetPy.
Some error occurred when I request data continuously over a period of time, the source codes are attached.
Look forwarding to you help.
```
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 281, in connect
    conn = self._new_conn()
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0318697be0>, 'Connection to hinetwww11.bosai.go.jp timed out. (connect timeout=60)')
```
```Python
#!/bin/env python
import datetime
import os
import glob
from HinetPy import Client
from HinetPy import win32

timeb = datetime.datetime(2016,11,8,23,30,0)
timee = datetime.datetime(2017,1,1,0,0,0)
span = 30
nowtime = timeb
clnt = Client('xxxxxx', 'xxxxxxx')

while nowtime < timee:
    dirname = nowtime.strftime("%Y%m%d%H%M")
    print(dirname)
    if os.path.isdir(dirname) and glob.glob(os.path.join(dirname, "*.SAC")):
        pass
    else:
        data, ctable = clnt.get_waveform('0101', dirname, span, outdir=dirname)
        win32.extract_sac(data, ctable, outdir=dirname)
        win32.extract_pz(ctable, outdir=dirname)
    nowtime += datetime.timedelta(minutes=span)
```

**Comment by xumi1993** [comment]
Some times an hour and some times several hours.

**Comment by seisman** [comment]
@xumi1993 I think it would be very difficult to debug network issues like this due to its unpredictability.

Maybe you can try move `clnt = Client('xxxxxx', 'xxxxxxx')` inside the `while` loop:
```python
#!/bin/env python
import datetime
import os
import glob
from HinetPy import Client
from HinetPy import win32

timeb = datetime.datetime(2016,11,8,23,30,0)
timee = datetime.datetime(2017,1,1,0,0,0)
span = 30
nowtime = timeb

while nowtime < timee:
    dirname = nowtime.strftime("%Y%m%d%H%M")
    print(dirname)
    if os.path.isdir(dirname) and glob.glob(os.path.join(dirname, "*.SAC")):
        pass
    else:
        clnt = Client('xxxxxx', 'xxxxxxx')
        data, ctable = clnt.get_waveform('0101', dirname, span, outdir=dirname)
        win32.extract_sac(data, ctable, outdir=dirname)
        win32.extract_pz(ctable, outdir=dirname)
    nowtime += datetime.timedelta(minutes=span)
```

**Comment by xumi1993** [comment]
Thanks, I will try it

**Comment by seisman** [comment]
@xumi1993 Does it work well?

**Comment by xumi1993** [comment]
It's still working till now. I will continuously test this case for few 1~2 days

**Comment by xumi1993** [comment]
Errors never raised again! Thanks.
